version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=coursera
  neo4jmicro:
    build:
      context: ./neo4jmicroservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    restart: on-failure
  mongodbmicro:
    build:
      context: ./Mongo4Exam
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: on-failure
  postgresmicro:
    build:
      context: ./Postgres4Exam
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: on-failure
  redismicro:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
    restart: on-failure
